name: Ruby

on: [push,pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby:
        - "3.1"
        os:
        - ubuntu
        - windows
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Build extension and gem
      run: |
        bundle install
        bundle exec rake build || type tmp/*/ruby_discord_game_sdk/3.1.1/Makefile
    - name: Format artifact
      run: bin/format-artifact.sh ${{ matrix.os }}
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ruby-discord-game-sdk-ruby${{ matrix.ruby }}-${{ github.sha }}
        path: artifact-upload
